### ISSUE TITLE
About the channel normalization layer?

### ISSUE THREAD

**Issue by bityangke** [colincsl/TemporalConvolutionalNetworks#3]
Hi,
Could you please tell me why normalize by the highest activation rather than using BN layer?
Thanks very much!

**Comment by colincsl** [comment]
I've never had good luck using BN on time-series data. I believe the issue is that the input feature distribution and output label distribution tends to be very different between batches (in 50 Salads e.g. in one trial a user may stand idle for a long time -- meaning there are a lot of "background" time steps -- whereas in another trial they may move constantly). We want the receptive field to be very long (e.g., 1 minute), so the duration of each sample must be long, and thus as a result the batch size will be relatively low. Additionally, these dataset are relatively small -- yet the distributions are fairly different -- so perhaps we don't have enough examples to learn good BN parameters. 

This type of (frame-wise) normalization helps with vanishing gradient issues. Note that the Normalized ReLU used here is similar to using a normal ReLU and then applying LayerNorm. When I wrote this paper I didn't know LayerNorm existed.

**Comment by bityangke** [comment]
Thanks very much!
I guess the reason is that dropout layer before BN layer makes performance poor.

**Comment by colincsl** [comment]
That's not actually the issue here, but that is another common mistake. :)
